<?php


/**
 * Herringbone Theme Template Part - Dev Landing Page - Competition Section.
 *
 * @package herringbone
 * @author Jefferson Real <me@jeffersonreal.com>
 * @copyright Copyright (c) 2021, Jefferson Real
 */
?>

<div class="landing_content cheese" style="--row: 1 / -1; --col: oneone-l / oneone-r;">
	<div class="column">

		<h2>What are the options for building a small business website?</h2>
		<h3>DIY Website Builders</h3>
		<p>Many small businesses attempt to put together a website using a DIY website builder such as Wix, Weebly or Squarespace. These options are better than no website at all, but only by a small margin.</p>
		<h4>SEO</h4>
		<p>They all advertise benefits, but besides putting your page titles in the right place, they make websites that are hard for search engines to make sense of. The auto-generated code that forms the structure of your website is rarely compliant with any best practice let alone covering the basics of the <a href="https://developers.google.com/search/docs/beginner/seo-starter-guide">Google SEO Optimization recommendations</a>. </p>
		<h4>Professionalism</h4>
		<p>Home-made websites look just that and if it’s not something you can proudly show your clients, it’s not likely to be winning you work over your competitors.</p>
		<h4>Control</h4>
		<p>You’ll be fixed in a rigid website template offering little room to implement features that might otherwise give you the edge and represent the brand as you want. The framework also won’t allow for easy adaption by a web developer leading to hacky workarounds that will be mostly non-reusable when you outgrow the platform.</p>
		<h4>Ownership</h4>
		<p>The website you see doesn’t belong to you. You don’t own the code or any of the visuals that have been generated for you so when it comes to expansion, addition, or even just wanting to move to a new host or provider, you start from scratch.</p>
		<h3>Cheap Web Designers</h3>
		<p>There are plenty of website designers who will offer their skills and provide you with a multi-page website for a reasonable cost. It will probably even look appealing but you’ll have to do all the bits they don’t do such as managing your hosting, domains and emails, then find your own ongoing support.</p>
		<p>Here’s a thought: Most website designers aren't developers which is to say writing code isn’t their strong point. So how do they put together a working website? The website you’ll end up with will likely have been built using a drag and drop page-builder which allows them to build a websites without any programming knowledge. They can then offer a cheap website with limited bespoke styling for a great price.</p>
		<h4>No Updates</h4>
		<p>The website built on the page builder software is version-locked as the license for continued updates is owned by the person who built the website. There will come a point where the supporting server environment cannot be updated because the latest server software conflicts with the version-frozen website platform. You may begin to see performance degradation and certain features begin to break as the website server gets more out of date, and security will be a huge concern. Solution: rebuild from scratch.</p>
		<h4>Ownership</h4>
		<p>Unfortunately, it’s the same as the DIY website builder. You don’t own the code generated by the page-builder software so any further development or upgrades will have to work around the unlicensed framework leaving a clunky hybrid between hand-written code and page-builder or more likely: investment in a new website build.</p>
		<h3>Website Agency</h3>
		<p>This is the traditional go-to for a professional, bespoke website with all the relevant skills under one roof, or at least the in-house knowledge to project manage resources to build you anything you want. But with that high-street office comes overheads: rental, bills and employee benefits are all tacked on to your bill before you even begin to price up the website.</p>
		<p>It’s also understandable that agencies prefer big projects, something big enough to keep the whole team active at once as opposed to disruptive bit-work. They’ll be used to frequently submitting tenders for tens of thousands and it’s likely your small business won’t be high on the priority list.</p>

	</div>
</div>

<div class="landing_backdrop">
</div>
